### ISSUE TITLE
Update the Guide

### ISSUE THREAD

**Issue by jessmartin** [webnative-examples/webnative-app-template#14]
## Motivation

We have made some fundamental changes to the way that WebNative works, including extending core components. All of those changes / options should be reflected in the Guide.

## Finish Line

NOTE: Some of these sections will be duplicated in the README (See #13) with a slightly different emphasis.

- [x] Document initialization options 
- [x] Document authentication options (Lobby versus no Lobby)
- [x] Document account linking: dependency injection options
    - It might be helpful to show an example, at least in pseudocode, of how these dependency injections work. @bgins mentioned that a possible example could be showing a "matched pair" of a `delegateAccount` and `linkDevice` functions being passed during account linking to demonstrate sending additional secrets. Nice opportunity to emphasize the fact that device linking occurs over a secure channel!

**Comment by therealjeffg** [comment]
Note: changes here are dependant on upcoming Webnative refactoring. This is nice to have for Milestone 0.2 but we will ship the blog post w/o this if necessary.

**Comment by avivash** [comment]
Flagging here that we should add a section to the guide about how we can't currently support Firefox as a first-class platform, based on this convo https://discord.com/channels/478735028319158273/934505479902748672/1039262334071341098

**Comment by therealjeffg** [comment]
> Flagging here that we should add a section to the guide about how we can't currently support Firefox as a first-class platform, based on this convo https://discord.com/channels/478735028319158273/934505479902748672/1039262334071341098

I think this needs more testing. I just tried with a fresh profile on Firefox nightly ( so default settings ) and linking to the published webnative app worked *on the second try*. Huh.

**Comment by therealjeffg** [comment]
This is now done and will be deployed in early January. Unresolved: jess made a bunch of comments in Gitbook, *someone* should resolve these comments.

( some of these have all be done )

**Comment by bgins** [comment]
The guide updates have been completed and are live at https://guide.fission.codes/developers/webnative
