### ISSUE TITLE
Blog Post Announcing Initial Release

### ISSUE THREAD

**Issue by jessmartin** [webnative-examples/webnative-app-template#15]
## Motivation

We want people to use this template to build stuff. So we should do our best to publicize it.

## Finish Line

- [ ] Blog post on the Fission blog

**Comment by therealjeffg** [comment]
Current status - @walkah is going to talk to Becky wrt who is writing this thing.

**Comment by jessmartin** [comment]
Targeting 11/8 or 11/9 for the blog post.

**Comment by avivash** [comment]
@therealjeffg do you have the keys to `webnative.dev`? we're hoping to map it to the new site once the newsletter signup is ready(which it sounds like it almost is)
