### ISSUE TITLE
Quick demo video for YouTube (TikTok?)

### ISSUE THREAD

**Issue by jessmartin** [webnative-examples/webnative-app-template#16]
## Motivation

We want people to use this template to build stuff. So we should do our best to publicize it.

## Finish Line

- [ ] Punchy, short overview video of using the template to build an app? Or walking through it?

Check out [this video](https://www.youtube.com/watch?v=oTQXzhm8w_8) for an example of short and punchy overview (100k+ views!!

**Comment by walkah** [comment]
We have the speed run!
