### ISSUE TITLE
Add "relentless explanation mode"?

### ISSUE THREAD

**Issue by therealjeffg** [webnative-examples/webnative-app-template#56]
Should we implement some sort of "extra explanations" mode for developers kicking the tires of the app template that goes into more depth.

**Comment by therealjeffg** [comment]
Alternative: some separate "wtf just happened" piece of info.

**Comment by therealjeffg** [comment]
Alternative: first run experience?

**Comment by therealjeffg** [comment]
Alternative - should we build an app that is an illustrated Primer for understanding webnative?

**Comment by walkah** [comment]
Closing for now
