### ISSUE TITLE
Improve homepage UI

### ISSUE THREAD

**Issue by bgins** [webnative-examples/webnative-app-template#58]
The UI for the homepage was assembled quickly without a design spec. It could definitely be improved.

A user sees two different views of the homepage. Before they register, they see an unauthed view

<img width="1920" alt="before-registration" src="https://user-images.githubusercontent.com/7957636/188912521-95fc4726-e395-4613-a9a7-b7da5eb1acca.png">

After they register they see an authed view

<img width="1920" alt="after-registration" src="https://user-images.githubusercontent.com/7957636/188912570-f4a74e29-e808-4dec-91ca-52841fe50405.png">

The About section is displayed in both cases, but the Account and Photo Gallery Demo sections are only displayed when authed.

@depatchedmode could you suggest some improvements for this page?

**Comment by depatchedmode** [comment]
Tracking in [Trello](https://trello.com/c/84MKJWZ4/39-wn-improve-homepage-ui)

**Comment by depatchedmode** [comment]
![image](https://user-images.githubusercontent.com/84613835/199556216-793f92de-c2e2-4444-ab58-74b8bf4b5bbc.png)

**Comment by bgins** [comment]
Amazing! This looks fantastic! ✨ Same with the one in #59.
