### ISSUE TITLE
Add a User route

### ISSUE THREAD

**Issue by therealjeffg** [webnative-examples/webnative-app-template#59]
Should probably include info about the current account plus access to a recovery kit download link.

UI question from @bgins - does this justify putting the hamburger menu back in?

**Comment by depatchedmode** [comment]
Tracking in [Trello](https://trello.com/c/84MKJWZ4/39-wn-improve-homepage-ui)

**Comment by depatchedmode** [comment]
Hey - just about to start on the designs for this. What should go on this page? Do we still have a recovery kit, or is that now deferred along with the improved account recovery flows in general?

**Comment by avivash** [comment]
> Hey - just about to start on the designs for this. What should go on this page? Do we still have a recovery kit, or is that now deferred along with the improved account recovery flows in general?

@depatchedmode it looks like the recovery flow work is part of the Alpha 0.3 release now, so maybe we should hold off on adding the recovery kit download until that work has been done https://github.com/webnative-examples/webnative-app-template/issues/55

**Comment by bgins** [comment]
@depatchedmode agreed with @avivash that we could hold off on the recovery kit download for now. We will eventually want it for both filesystem-only recovery and full account recovery (the latter with email or social recovery in the loop).

Aside from the recovery kit, this page could include username and the current backup status (has the account been linked on another device).

**Comment by depatchedmode** [comment]
@bgins What info can we show the user about the other devices that have been linked? Is it just a binary "no other devices vs some other devices"? Or can we show some type of identifying information that would help the user recognize their linked devices?

**Comment by bgins** [comment]
@depatchedmode in the current implementation, it's a binary "no other devices vs some other devices".

In a future iteration, we could store some information about which devices the user has linked. Most likely the easiest path would be each device writes an entry for itself to WNFS. Likely a discussion for somewhere else, but what kind of information would help users to identify their connected devices?

**Comment by depatchedmode** [comment]
Here's the initial iteration. Added a username and avatar field (which we can remove for now).
![image](https://user-images.githubusercontent.com/84613835/199556360-8765d547-81e2-4a1a-ba22-1404db189438.png)
