### ISSUE TITLE
Provide a debug flag and related debug component

### ISSUE THREAD

**Issue by therealjeffg** [webnative-examples/webnative-app-template#7]
As a developer, I would love to be able to enable a "debug" flag that enables a related debug UI component in my app that provides some insight into the internal state of the app, in particular the webnative state.

This view would be a spiritual successor of the django debug toolbar:

https://github.com/jazzband/django-debug-toolbar

As part of this, I suspect the best approach would be to provide this as a svelte component that takes a prop "debug=false" by default, and if the debug prop is false the component is a no-op. If debug is true it provides a UI that lets the developer inspect the wn object and various useful things like current user details / session state.

**Comment by therealjeffg** [comment]
Aside: I think this is a fast-follow for this template, not a must-have for the first version.

**Comment by walkah** [comment]
This is probably a separate project
