### ISSUE TITLE
Support relative links

### ISSUE THREAD

**Issue by bmann** [webnative-examples/webnative-app-template#8]
When apps get loaded on arbitrary gateways — EG `gateway.com/ipfs/APPHASH` or `gateway.com/ipns/APPNAME.fission.app`— then an app will break and/or at least visually break when CSS and other styling assets don’t load. 

The template should work out of the box to build with relative links, so that it can be loaded in any IPFS context. 

We run a relative links filter as part of building @fission-suite/landing-page that may be helpful to look at.

**Comment by therealjeffg** [comment]
Scope for 0.1 is just to support fission publishing.

**Comment by jessmartin** [comment]
Fission publishing didn't work because of a lack of redirect support in IPFS gateways, so we went with deployment to Netlify for now. See #50.
