### ISSUE TITLE
People click on offsite links and don’t try app

### ISSUE THREAD

**Issue by bmann** [webnative-examples/webnative-app-template#80]
In my in person testing (primarily on mobile), people will click on links in the About Block rather than try the app. 

Suggest rewriting the About block to describe what this demo does, and either including a “Connect” button or directing people to click Connect to get started. 

Links to dev content can be moved to an actual About page.

**Comment by avivash** [comment]
This has been addressed as part of https://github.com/webnative-examples/webnative-app-template/issues/58

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/1179291/200392541-52bfdcf2-2d99-459f-8289-0ef94900a3a4.png">

**Comment by therealjeffg** [comment]
Closing, this work is done in #58
