### ISSUE TITLE
Update README to explain new Webnative APIs

### ISSUE THREAD

**Issue by jessmartin** [webnative-examples/webnative-app-template#86]
Once we update to [the massively refactored Webnative](https://github.com/fission-codes/webnative/pull/422), 
the README and the [Fission Guide](https://guide.fission.codes/) will need to be updated to explain the new APIs.

**Comment by bgins** [comment]
The [Webnative README](https://github.com/fission-codes/webnative/blob/main/README.md) and [Fission Guide](https://guide.fission.codes/developers/webnative) have been updated with information on the latest APIs.
