### ISSUE TITLE
Add recovery kit

### ISSUE THREAD

**Issue by bgins** [webnative-examples/webnative-app-template#91]
# Summary

## Problem

Users cannot recover their filesystem without a copy of their read key.

### Impact

A user could irrevocably lose the private data they have stored in WNFS.

## Solution

Create an account recovery kit that includes:

- Username (to look up their filesystem)
- Read key (to decrypt their filesytem root)

The user should be able to download a recovery kit for safe keeping and later upload it to recover their filesystem.

Most likely the recovery kit should be a text file for ease of creation and parsing.

The existing account recovery flow has some prior art: https://guide.fission.codes/accounts/account-signup/account-recovery. This flow uses a recovery kit as text file which might be a good starting point.

**Comment by depatchedmode** [comment]
> Most likely the recovery kit should be a text file for ease or creation and parsing.

Out of curiosity, have other options been proposed?

**Comment by avivash** [comment]
> > Most likely the recovery kit should be a text file for ease or creation and parsing.
> 
> Out of curiosity, have other options been proposed?

we haven't proposed other options yet. I think the text file idea came from the thought that it was the easiest solution in terms of simple download/upload/parsing(though i guess the question is: is it easier for us or the users? 😅). I kind of like this approach too where you just tell the user to save the values to their password manager(though having a download as an additional option seems like it may be a good idea) https://dribbble.com/shots/18325312-Password-Recovery?showSimilarShots=true&_=1668801048112

**Comment by bgins** [comment]
> I kind of like this approach too where you just tell the user to save the values to their password manager(though having a download as an additional option seems like it may be a good idea) https://dribbble.com/shots/18325312-Password-Recovery?showSimilarShots=true&_=1668801048112

Oh yeah, that's a neat approach. It would be interesting to know if there are any stats on how widely used password managers are. I've heard that's it mostly tech inclined people that use them, but that might be wrong.

**Comment by avivash** [comment]
> > I kind of like this approach too where you just tell the user to save the values to their password manager(though having a download as an additional option seems like it may be a good idea) https://dribbble.com/shots/18325312-Password-Recovery?showSimilarShots=true&_=1668801048112
> 
> Oh yeah, that's a neat approach. It would be interesting to know if there are any stats on how widely used password managers are. I've heard that's it mostly tech inclined people that use them, but that might be wrong.

Yeah, based on my experience, most less technical people don't really use password managers. Ryan and I also floated the idea of adding buttons from various storage providers, such as a Save to iCloud and Save to Google Drive. 1Pass also has a Save to 1Pass button we can use. I'm sure other password managers have some ready-to-go buttons too 👍🏼

**Comment by depatchedmode** [comment]
> I've heard that's it mostly tech inclined people that use them, but that might be wrong.

Here in lies the problem. I don't want to blow scope wide open on this initial port from Fission Dashboard -> Webnative Application Template, but I suspect non-technical people will struggle to do the right thing with the recovery kit as a text file.

**Comment by bgins** [comment]
> Here in lies the problem. I don't want to blow scope wide open on this initial port from Fission Dashboard -> Webnative Application Template, but I suspect non-technical people will struggle to do the right thing with the recovery kit as a text file.

Our goal is to ship this by early January, so we have a bit of time to consider alternatives. This piece shouldn't block the overall filesystem recovery work.

Is the concern that the recovery kit is a text file or a file in general? Would a PDF or some other file format be better?

What are some alternatives to a recovery kit file?

**Comment by therealjeffg** [comment]
We discussed this today and concluded that:

1. it feels incomplete / a devex problem that WAT does not allow for account recovery out of the box.
2. at the same time, a conventional account recovery loop requires eg an email confirmation loop.

@depatchedmode there's sort of an existential issue in here that I think is fundamentally  a security / design issue that we need to talk through. Perhaps this is all neatly solved by passkeys + extra webnative elf magic.

**Comment by depatchedmode** [comment]
@therealjeffg Agreed. Sharing another example from 1Password's recovery flow, as additional evidence of the scale of this problem.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/84613835/207729548-336285ec-4519-4995-a4c6-ca6676129a67.png">
